### PR TITLE
feat: Validator extension

### PR DESCRIPTION
**Pull request by volovyk-s**
Validator extension works at this point, but I can not say that I'm happy with the result. Here is the path that I suggest we should follow in the future:
- [x] use [near-jsonrpc-client-rs](https://github.com/near/near-jsonrpc-client-rs) instead of `nearcore`
- [ ] use macros from [this](https://github.com/near/near-cli-rs/issues/47) PR (after the merge)
- [ ] create `near-cli-builder` crate inside of this repo, use it in the core project and validators extension (now `validators` extension is a separate project)

In general, 5000+ lines of code for an extension with 2 commands is too much. Even after the creation of macros mentioned above, we will not reach the point when users will be able to build new extensions without pain. I hope that a bunch of macros and libraries mentioned in [this](https://github.com/near/near-cli-rs/pull/66) PR will solve these issues.

### CODE REVIEW

**Comment by frol** [comment]
From the first glance, the extension is totally fine from the implementation point of view, though I would spend a few moments thinking through the structure (your README features `near validator list` while the implementation expects `near validator validators`; both variants are a bit odd for different reasons)

> In general, 5000+ lines of code for an extension with 2 commands is too much.

I totally agree. I feel sorry that you had to do it manually. Nobody should struggle over and over again here!

> Even after the creation of macros mentioned above, we will not reach the point when users will be able to build new extensions without pain. I hope that a bunch of macros and libraries mentioned in this PR will solve these issues.

I also have high hopes for that. I hope we can get to the point where we can have so little code that there is nothing to remove from it. Would you simply use clap, your CLI implementation would fit in a few hundred lines. We should definitely challenge ourselves to reach that state with the available automation (derive macros, generics, etc).

**Comment by frol** [comment]
@FroVolod Please, refactor validators extension to interactive-clap and create a separate branch to compare

**Comment by frol** [comment]
@volovyk-s Hey, check out this refactored version using the interactive-clap macro: https://github.com/near/near-cli-rs/tree/validator-extension-interactive-clap/extensions/validator/src

**Comment by Buckram123** [comment]
@frol  Build fails on my machine
```
error: failed to download `near-account-id v0.11.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/anymacstore/.cargo/registry/src/github.com-1ecc6299db9ec823/near-account-id-0.11.0/Cargo.toml`

Caused by:
  feature `edition2021` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["edition2021"]` to enable this feature
```
shouldn't `rust-toolchain` be updated to 1.56.0+?

**Comment by frol** [comment]
@Buckram123 This PR should be closed in favor of https://github.com/near/near-cli-rs/tree/validator-extension-interactive-clap/extensions/validator/src

**Pull request closed without merging**
