### PR TITLE
feat: Keychain access

### PR DESCRIPTION
**Pull request by Buckram123**
Keychain access for OS X users #98, If I did understand it correctly

### CODE REVIEW

**Comment by frol** [comment]
@Buckram123 The issue implied that the solution should also solve the usage part of the problem (thus, not only get the keys stored, but also let those be used whenever it is applicable - signing transactions).

Also, it should be conditionally compiled for MacOS as currently this PR broke compilation on all the rest platforms (see CI)

**Comment by frol** [comment]
Keep in mind that a single account can have multiple keys attached to it, and also a single near-cli-rs user might want to orchestrate multiple accounts.

**Comment by frol** [comment]
FYI, I am yet to see how the created key from the keychain can be used.

**Comment by Buckram123** [comment]
>  but also let those be used whenever it is applicable - signing transactions

Now signing transaction with OSX keychain also implemented, thanks.

**Comment by frol** [comment]
I got really underwater with other projects. I will review this PR today

**Comment by frol** [comment]
It is a great starting point, and it is good to know that we can just store the whole JSON with the secret & public keys as well as the seed phrase, etc. Yet, it is not usable, as it requires the user to specify their public key which makes it hard to use. What I suggested before is to use `~/.near-credentials` always, but store only account id, public key, and the secure storage kind or reference, so with the keychain, it could look like:

```json
{
  "account_id": "frol.near",
  "public_key": "ed25519:...",
  "storage_kind": "macos_keychain"
}
```

Then you won't need to bother users asking their public key

**Comment by frol** [comment]
This PR was superseeded by #122 and MacOS keychain support is already merged into master

@Buckram123 Thank you for paving the road for this feature!

**Pull request closed without merging**
