### PR TITLE
Implement CLI for sending meta transactions to relayer

### PR DESCRIPTION
**Pull request by anthony-near**
Solves https://github.com/near/near-cli-rs/issues/141 by adding CLI support for sending a `SignedDelegateAction` to a relayer. 

Based on Nearcore implementation (mainly `near_primatives`) with meta tx support https://github.com/near/nearcore/pull/7497/

### CODE REVIEW

**Comment by frol** [comment]
@anthony-near Thanks for championing the implementation! I will get to review it tomorrow

**Comment by anthony-near** [comment]
@frol sounds good. Here's the general flow I used to test:
```
awit@Anthonys-MacBook-Pro near-cli-rs % cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.36s
     Running `target/debug/near-cli`
✔  What are you up to? (select one of the options with the up-down arrows on your keyboard and press Enter) · transaction - Operate transactions
✔ Сhoose action for transaction · construct-transaction  - Construct a new transaction
What is the sender account ID?: nomnomnom.testnet
What is the receiver account ID?: relayer_test0.testnet
✔ Select an action that you want to add to the action: · add-action   - Select a new action
✔ Select an action that you want to add to the action: · send-near            - The transfer is carried out in NEAR tokens
How many NEAR Tokens do you want to transfer? (example: 10NEAR or 0.5near or 10000yoctonear): 1yoctonear
✔ Select an action that you want to add to the action: · skip         - Skip adding a new action
✔ What is the name of the network? · testnet
✔  Select a tool for signing the transaction · sign-with-keychain               - Sign the transaction with a key saved in legacy keychain (compatible with the old near CLI)

Your transaction was signed successfully.
Signed transaction:

signer_id:    nomnomnom.testnet
public_key:   ed25519:89GtfFzez3opomVpwa7i4m3nptHtc7Ha514XHMWszQtL
nonce:        103066617000626
receiver_id:  relayer_test0.testnet
block_hash:   8aNp8rrux26jK8BzKwyJC5bnSenw1VLKMvAi4aBEzpN8
actions:
   -- transfer deposit:    0.000000000000000000000001 NEAR

✔ How would you like to proceed · send via relay     - Send to a relayer
Enter relayer endpoint (ie http://relayer.near.org:3030/relay) : http://127.0.0.1:3030/relay
Sending SignedDelegateAction to relayer [17, 0, 0, 0, 110, 111, 109, 110, 111, 109, 110, 111, 109, 46, 116, 101, 115, 116, 110, 101, 116, 21, 0, 0, 0, 114, 101, 108, 97, 121, 101, 114, 95, 116, 101, 115, 116, 48, 46, 116, 101, 115, 116, 110, 101, 116, 1, 0, 0, 0, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 179, 50, 24, 17, 189, 93, 0, 0, 108, 219, 62, 7, 0, 0, 0, 0, 0, 106, 32, 108, 48, 41, 239, 130, 56, 251, 184, 223, 160, 135, 190, 178, 200, 246, 109, 168, 92, 10, 10, 115, 5, 220, 50, 157, 201, 56, 71, 110, 5, 0, 237, 240, 16, 69, 88, 84, 204, 57, 94, 75, 197, 227, 203, 232, 126, 83, 157, 6, 101, 234, 152, 10, 222, 215, 118, 229, 189, 48, 13, 48, 231, 54, 17, 33, 82, 88, 222, 122, 103, 101, 99, 35, 173, 201, 210, 110, 219, 159, 120, 28, 11, 116, 213, 61, 158, 79, 59, 178, 112, 154, 112, 55, 42, 15]
Relayer Response text: {"Transaction Outcome Logs":"","message":"Successfully relayed and sent transaction.","status":{"SuccessValue":""}}
Your console command:
target/debug/near-cli transaction construct-transaction nomnomnom.testnet relayer_test0.testnet add-action send-near '0.000000000000000000000001 NEAR' skip network-config testnet sign-with-keychain
```
replace the localhost relayer endpoint with https://relayer-sweat-testnet-7tk2cmmtcq-uc.a.run.app/relay

You'll also need to replace the sender account id `nomnomnom.testnet` with a testnet credentials contained in your `.near-credentials` directory on your machine you're running the cli on

**Comment by frol** [comment]
@anthony-near It seems that the relay service is no longer available. @FroVolod [is currently working on getting meta-transactions support](https://github.com/near/near-cli-rs/compare/update-near-library), and gets HTTP 503 response:

image

Is there a new URL?

Also, it is known to take unnecessarily more CPU time and traffic to send an array of JSON numbers (`[123, 125]` - 10 bytes to encode `{}`) than e.g. base64 string in JSON (`"e30="` - 6 bytes to encode `{}`), so I suggest that relayer expects the following payload:

```json
{
  "signed_delegate_action": "base64-encoded-signed-delegate-action"
}
```

This way it will be much easier to introduce more fields if necessary (compared to the case when you expect to receive an array of numbers), has better performance, uses less traffic, and is easier to reason about as the field is clearly named.

P.S. @FroVolod [succeeded](https://explorer.testnet.near.org/accounts/fro_test7.testnet) in getting meta-transaction submitted from CLI! 🎉

**Comment by anthony-near** [comment]
@frol try this endpoint 34.70.226.83:3030/relay. 

Regarding the 64 encoding, that's something we can do but it would require changes in this library, js cli, and on the relayer. May I suggest if you're looking for an alternative that you try the `/send_meta_tx` endpoint (34.70.226.83:3030/send_meta_tx) which is json serialized (no borsh) with payload looking like:
```
{
    "delegate_action": {
        "actions": [
            {
                "Transfer": {
                    "deposit": "1"
                }
            }
        ],
        "max_block_height": 122790412,
        "nonce": 103066617000686,
        "public_key": "ed25519:89GtfFzez3opomVpwa7i4m3nptHtc7Ha514XHMWszQtL",
        "receiver_id": "relayer_test0.testnet",
        "sender_id": "nomnomnom.testnet"
    },
    "signature": "ed25519:5uJu7KapH89h9cQm5btE1DKnbiFXSZNT7McDw5LHy8pdAt5Mz9DfuyQZadGgFExo88or9152iwcw2q12rnFWa6bg"
}
```

**Comment by frol** [comment]
@anthony-near Both endpoints work fine! (getting HTTP 400 with the following message, which I believe it totally expected: "Delegate Action receiver_id frol13.testnet or sender_id frol14.testnet is not whitelisted OR (they do not match AND the NonDelegateAction is not AddKey)")

**Comment by frol** [comment]
Resolved in #189

**Pull request closed without merging**
