### PR TITLE
chore: add `apple-native`, `windows-native`, `sync-secret-service` feature in `dep:keyring` 

### PR DESCRIPTION
**Pull request by dj8yfo**

### CODE REVIEW

**Review by akorchyn — COMMENTED** [review]
Looks good. I just think if it can fail on other platforms cause of all the features we pull together

**Review by akorchyn — APPROVED** [review]
I could manage to sing tx on NixOS. But I have compiled on my own, because using precompiled binaries is tricky :)

**Comment by akorchyn** [comment]
@race-of-sloths score 5

**Comment by frol** [comment]
I am closing this one in favor of #392

**Pull request closed without merging**
