### PR TITLE
feat: Added ability to edit configuration parameters

### LINKED ISSUE #305: Option to run non-interactive cli
One of the best things about this tool is it's interactivity -- however, without the option to disable it, this interactivity can cause issue in non-interactive containers.

For example, attempting to use `near config add-connection --network-name mainnet --connection-name mainnet --rpc-url https://rpc.mainnet.near.org/ --wallet-url https://app.mynearwallet.com/ --explorer-transaction-url https://nearblocks.io/txns/` (which holds all of the information I want to provide) asks me several questions that cause `The input device is not a TTY` errors in my container (git workflow).

If you see the screenshot below, I don't think any of these questions needed my explicit answers and could have been assumed/ignored.

Screenshot 2024-02-21 at 12 15 51 PM

I think this could be solved with a --non-interactive flag

### LINKED ISSUE #365: [Enhancement] Add an option to edit configs
We are currently at a hackathon, and the official RPC went down. It would be nice to be able to quickly edit the fields on the existing config, so users can change RPC in seconds.

### PR DESCRIPTION
**Pull request by FroVolod**
Resolves #365, resolves #305

### CODE REVIEW

**Comment by FroVolod** [comment]
@race-of-sloths

**Comment by race-of-sloths** [comment]
@FroVolod Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
New Sloth joined the Race! Welcome!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/FroVolod?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/FroVolod?type=bot&theme=light">
    Shows profile picture for the author of the PR
</picture>](https://race-of-sloths.com/profile/FroVolod)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command
</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/FroVolod)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Review by frol — APPROVED** [review]
@race-of-sloths score 5

**Comment by race-of-sloths** [comment]
### 🌟 Score recorded!

@frol, thank you for scoring this pull request in the Race of Sloths!

**Comment by race-of-sloths** [comment]
### ✅ PR is finalized! 
Your contribution is much appreciated with a final score of 5!
You have received 60 (50 base + 10 weekly bonus) Sloth points for this contribution


Another weekly streak completed, well done @FroVolod! To keep your weekly streak and get another bonus make pull request next week! Looking forward to see you in race-of-sloths

**Pull request merged**
